# Generated by Django 5.2.4 on 2025-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copyright',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
